### ISSUE TITLE
XMLhttp error

### ISSUE THREAD

**Issue by MySwastik** [jaxnz/flutter_google_places_web#7]
Error: DioError [DioErrorType.response]: Http status error [403]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28   get current
packages/dio/src/dio_mixin.dart 819:20.
Please solve this..
![Inkederror_LI](https://user-images.githubusercontent.com/64435239/126056075-b4d7ce0f-1a08-4ba0-a465-b992e5905471.jpg)

**Comment by jaxnz** [comment]
Hi,

That is because you are using the default CORS-anywhere proxy - which has now been taken down due to abuse.

You can use the same CORS-anywhere proxy with your own server (or create one with Herokuapp)

[CORS Anywhere](https://github.com/Rob--W/cors-anywhere)

Unfortunately at this time, Google Places API don't support any CORS support on their end, so a proxy will be needed.

Jackson

**Comment by MySwastik** [comment]
Thanks for support.
